

const constants = {

    GET_CUSTOMER: "GET_CUSTOMER",
    GET_CUSTOMERS: "GET_CUSTOMERS",
    GET_USER: "GET_USER",
    UPDATE_CONTENT_HEIGHT: "UPDATE_CONTENT_HEIGHT",
    UPDATE_SIDEBAR_HEIGHT: "UPDATE_SIDEBAR_HEIGHT",
    UPDATE_SIDEBAR_CLASS: "UPDATE_SIDEBAR_CLASS",
    UPDATE_CONTENT_RIGHT_TYPE: "UPDATE_CONTENT_RIGHT_TYPE",
    UPDATE_CONTENT_RIGHT_OPEN: "UPDATE_CONTENT_RIGHT_OPEN"

};

export default constants;



