

const constants = {

    GET_CUSTOMERS: "GET_CUSTOMERS",
    GET_USER: "GET_USER",
    UPDATE_CONTENT_HEIGHT: "UPDATE_CONTENT_HEIGHT",
    UPDATE_SIDEBAR_HEIGHT: "UPDATE_SIDEBAR_HEIGHT",
    UPDATE_SIDEBAR_CLASS: "UPDATE_SIDEBAR_CLASS"

};

export default constants;



