

const constants = {

    GET_USER: "GET_USER",

    GET_CUSTOMER: "GET_CUSTOMER",
    GET_CUSTOMERS: "GET_CUSTOMERS",    
    EDIT_CUSTOMER: "EDIT_CUSTOMER",
    CREATE_CUSTOMER: "CREATE_CUSTOMER",
    RESET_CUSTOMER: "RESET_CUSTOMER",
    DELETE_CUSTOMER: "DELETE_CUSTOMER",
    
    GET_CONTACT: "GET_CONTACT",
    GET_CONTACTS: "GET_CONTACTS",
    EDIT_CONTACT: "EDIT_CONTACT",
    CREATE_CONTACT: "CREATE_CONTACT",
    DELETE_CONTACT: "DELETE_CONTACT",
    
    UPDATE_CONTENT_HEIGHT: "UPDATE_CONTENT_HEIGHT",
    UPDATE_SIDEBAR_HEIGHT: "UPDATE_SIDEBAR_HEIGHT",
    UPDATE_SIDEBAR_CLASS: "UPDATE_SIDEBAR_CLASS",
    UPDATE_CONTENT_RIGHT_TYPE: "UPDATE_CONTENT_RIGHT_TYPE",
    UPDATE_CONTENT_RIGHT_OPEN: "UPDATE_CONTENT_RIGHT_OPEN"

};

export default constants;



